# ????? ???????? ????????? ? JVM ????? ???????? ?????? ????????????
# ????? ??????(???????? ??????? ????? ???????) -> Edit Configurations
# -> ?????? ?? ?????? Modify options -> Add VM Options -> ???????? ? ???? VM options ?? ??? ????

# -Djava.util.logging.config.file=logging.properties

.level=ALL

# ????????? ???? ??? ?????
handlers=java.util.logging.ConsoleHandler, java.util.logging.FileHandler
java.util.logging.FileHandler.formatter = java.util.logging.SimpleFormatter
java.util.logging.FileHandler.append = true
java.util.logging.FileHandler.pattern = log.%u.%g.txt

# ????????? ???? ??? ???????
java.util.logging.ConsoleHandler.level=ALL
java.util.logging.ConsoleHandler.formatter = java.util.logging.SimpleFormatter

